milestone: 1 Todo review
bronnie313/Todo-review pull request #1
Opened 2023-05-08 10:56 UTC by bronnie313

## Todo List project 

- create new repository for a code review
- add Todo list project and implemented it's functionality 
- added a new directory for modules 
- installed linters and Webpack

2023-05-09 06:23 UTC, ankitt26 requested changes
Hi @bronnie313 

great job so far . There are some issues that you still need to work on to go to the next project but you are almost there!
# Required Changes ♻️

To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally


Check the comments under the review

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6d333836347242777742544b4d4162706e332f67697068792e676966](https://user-images.githubusercontent.com/108623895/237004279-ec9eb892-cd65-4e07-b6ba-cac2881e05b3.gif)

Check the comments under the review - 

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

2023-05-09 06:23 UTC, ankitt26 commented on src/index.js
> +  localStorage.setItem('tasks', JSON.stringify(listName));
- [ ] I think It could be better to use  ```localStorage.setItem('tasks', JSON.stringify(listName));```  inside a function and call it whenever needed, this allows you to follow JavaScript best practices.

2023-05-09 06:23 UTC, ankitt26 commented on src/index.js
> +    localStorage.setItem('tasks', JSON.stringify(listName));
- [ ] Please remove this line and call a function here instead of repeating your code

2023-05-09 06:23 UTC, ankitt26 commented on src/index.js
> +    localStorage.setItem('tasks', JSON.stringify(listName));
- [ ] Please remove this line L41 & L59  also and call a function here instead of repeating your code

2023-05-09 06:23 UTC, ankitt26 commented on src/modules/displayTask.js
> +  const listName = localStorage.getItem('tasks') ? JSON.parse(localStorage.getItem('tasks')) : [];
- [ ] I think It could be better to use  ```localStorage.getItem('tasks')```  inside a function and call it whenever needed, this allows you to follow JavaScript best practices. You can also use a new module to export a function and call it inside ```index.js``` and ```displayTask.js ```

2023-05-09 06:23 UTC, ankitt26 commented on src/modules/displayTask.js
> +    });
- [ ]  same here please  use  ```localStorage.setItem('tasks', JSON.stringify(listName));```  inside a function and call it whenever needed, this allows you to follow JavaScript best practices. You can also use a new module to export a function and call it inside ```index.js``` and ```displayTask.js ```

2023-05-09 06:23 UTC, ankitt26 commented on src/modules/displayTask.js
> +        currentUrl.reload();
- [ ] I am confused why you used this. Can you please tell me why you used this? ```currentUrl.reload();``` Is not a function and it producing an error in the browser console .

2023-05-09 06:23 UTC, ankitt26 commented on src/modules/displayTask.js
> +  for (let i = 0; i < listName.length; i += 1) {
- [ ] I think for Best Javascript practices it could be better to use ```for each ``` loop instead of old ``` for ``` loop

2023-05-09 08:21 UTC, bronnie313 commented on src/modules/displayTask.js
> +  for (let i = 0; i < listName.length; i += 1) {
thanks for reviewing my code I'm going to update all your reviews

2023-05-09 10:33 UTC, bronnie313 commented on src/modules/displayTask.js
> +        currentUrl.reload();
The code currentUrl.reload() is attempting to reload the current webpage using the reload() method of the Location object.

2023-05-09 11:56 UTC, ankitt26 commented
You did a great job in index.js file 👍, do the same here in displayTask.js also 👀

2023-05-09 14:24 UTC, ankitt26 commented on src/modules/displayTask.js
> +        currentUrl.reload();
Thanks 🙂

2023-05-10 10:20 UTC, ankitt26 approved these changes
Hi @bronnie313  ,

✅ Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![giphy](https://github.com/bronnie313/Todo-review/assets/108623895/ecacb36c-75d3-46c6-8373-062f3b380516)

Highlights
Linters are passing successfully ✔️
Project is running successfully ✔️
Descriptive pull request ✔️

2023-05-10 11:02 UTC, bronnie313 commented
Thanks @ankitt26 for reviewing and approving my project

2023-05-12 05:30 UTC, merged